#FASE 1 
services:

  namenode:
    image: apache/hadoop:3.3.6
    container_name: namenode
    user: root
    hostname: namenode
    #command: >
     # sh -c "if [ ! -d /hadoop/dfs/name/current ]; then
      #         /opt/hadoop/bin/hdfs namenode -format -force;
       #      fi;
        #     /opt/hadoop/bin/hdfs namenode"
    #A versão abaixo ela é mais segura em produção
    #pois caso o volume falhe ou esteja vazio por algum motivo, ele não recria outro.
    command: >
      bash -c " if [ ! -f /hadoop/dfs/name/current/VERSION ]; then
                  echo 'Formatting NameNode...'; hdfs namenode -format -force;
                fi && hdfs namenode"
    environment:
      - HADOOP_CONF_DIR=/opt/hadoop/etc/hadoop
    volumes:
      - ./config/core-site.xml:/opt/hadoop/etc/hadoop/core-site.xml
      - ./config/hdfs-site.xml:/opt/hadoop/etc/hadoop/hdfs-site.xml
      - ./config/yarn-site.xml:/opt/hadoop/etc/hadoop/yarn-site.xml
      - ./config/capacity-scheduler.xml:/opt/hadoop/etc/hadoop/capacity-scheduler.xml
      - ./config/workers:/opt/hadoop/etc/hadoop/workers
      - ./config/mapred-site.xml:/opt/hadoop/etc/hadoop/mapred-site.xml
      - namenode_data:/hadoop/dfs/name
    ports:
      - "9870:9870"
      - "8020:8020"
    networks:
      - hadoop-net

  datanode1:
    image: apache/hadoop:3.3.6
    container_name: datanode1
    user: root
    hostname: datanode1
    command: ["hdfs", "datanode"]
    environment:
      - HADOOP_CONF_DIR=/opt/hadoop/etc/hadoop
    volumes:
      - ./config/core-site.xml:/opt/hadoop/etc/hadoop/core-site.xml
      - ./config/hdfs-site.xml:/opt/hadoop/etc/hadoop/hdfs-site.xml
      - ./config/yarn-site.xml:/opt/hadoop/etc/hadoop/yarn-site.xml
      - ./config/capacity-scheduler.xml:/opt/hadoop/etc/hadoop/capacity-scheduler.xml
      - ./config/workers:/opt/hadoop/etc/hadoop/workers
      - ./config/mapred-site.xml:/opt/hadoop/etc/hadoop/mapred-site.xml
      - datanode1_data:/hadoop/dfs/data
    depends_on:
      - namenode
    networks:
      - hadoop-net

  datanode2:
    image: apache/hadoop:3.3.6
    container_name: datanode2
    user: root
    hostname: datanode2
    command: ["hdfs", "datanode"]
    environment:
      - HADOOP_CONF_DIR=/opt/hadoop/etc/hadoop
    volumes:
      - ./config/core-site.xml:/opt/hadoop/etc/hadoop/core-site.xml
      - ./config/hdfs-site.xml:/opt/hadoop/etc/hadoop/hdfs-site.xml
      - ./config/yarn-site.xml:/opt/hadoop/etc/hadoop/yarn-site.xml
      - ./config/capacity-scheduler.xml:/opt/hadoop/etc/hadoop/capacity-scheduler.xml
      - ./config/workers:/opt/hadoop/etc/hadoop/workers
      - ./config/mapred-site.xml:/opt/hadoop/etc/hadoop/mapred-site.xml
      - datanode2_data:/hadoop/dfs/data
    depends_on:
      - namenode
    networks:
      - hadoop-net

  resourcemanager:
    image: apache/hadoop:3.3.6
    container_name: resourcemanager
    user: root
    hostname: resourcemanager
    command: ["yarn", "resourcemanager"]
    environment:
      - HADOOP_CONF_DIR=/opt/hadoop/etc/hadoop
    volumes:
      - ./config/core-site.xml:/opt/hadoop/etc/hadoop/core-site.xml
      - ./config/hdfs-site.xml:/opt/hadoop/etc/hadoop/hdfs-site.xml
      - ./config/yarn-site.xml:/opt/hadoop/etc/hadoop/yarn-site.xml
      - ./config/capacity-scheduler.xml:/opt/hadoop/etc/hadoop/capacity-scheduler.xml
      - ./config/workers:/opt/hadoop/etc/hadoop/workers
      - ./config/mapred-site.xml:/opt/hadoop/etc/hadoop/mapred-site.xml
    ports:
      - "8383:8088"
    depends_on:
      - namenode
    networks:
      - hadoop-net

  nodemanager1:
    image: apache/hadoop:3.3.6
    container_name: nodemanager1
    hostname: nodemanager1
    command: ["yarn", "nodemanager"]
    environment:
      - HADOOP_CONF_DIR=/opt/hadoop/etc/hadoop
    volumes:
      - ./config/core-site.xml:/opt/hadoop/etc/hadoop/core-site.xml
      - ./config/hdfs-site.xml:/opt/hadoop/etc/hadoop/hdfs-site.xml
      - ./config/yarn-site.xml:/opt/hadoop/etc/hadoop/yarn-site.xml
      - ./config/capacity-scheduler.xml:/opt/hadoop/etc/hadoop/capacity-scheduler.xml
      - ./config/workers:/opt/hadoop/etc/hadoop/workers
      - ./config/mapred-site.xml:/opt/hadoop/etc/hadoop/mapred-site.xml
    depends_on:
      - resourcemanager
    networks:
      - hadoop-net

  nodemanager2:
    image: apache/hadoop:3.3.6
    container_name: nodemanager2
    hostname: nodemanager2
    command: ["yarn", "nodemanager"]
    environment:
      - HADOOP_CONF_DIR=/opt/hadoop/etc/hadoop
    volumes:
      - ./config/core-site.xml:/opt/hadoop/etc/hadoop/core-site.xml
      - ./config/hdfs-site.xml:/opt/hadoop/etc/hadoop/hdfs-site.xml
      - ./config/yarn-site.xml:/opt/hadoop/etc/hadoop/yarn-site.xml
      - ./config/capacity-scheduler.xml:/opt/hadoop/etc/hadoop/capacity-scheduler.xml
      - ./config/workers:/opt/hadoop/etc/hadoop/workers
      - ./config/mapred-site.xml:/opt/hadoop/etc/hadoop/mapred-site.xml
    depends_on:
      - resourcemanager
    networks:
      - hadoop-net
    
  #FASE 2 adicionar um componente HIVE 

networks:
  hadoop-net:
    driver: bridge

volumes:
  namenode_data:
  datanode1_data:
  datanode2_data:
